### ISSUE TITLE
Question: difference between policy add-ons and placement

### ISSUE THREAD

**Issue by zghyy** [open-cluster-management-io/community#86]
I would like to know that both placement and policy add-ons can control the distribution of resources,
What is the difference between policy add-ons and placement

**Comment by mikeshng** [comment]
Placement is for determining which cluster(s) matches your criteria. Policy is for reporting/enforcing compliance on a cluster. Policy needs the placement to know which cluster(s) to report/enforce on. So together policy and placement can be used to delivery workload.

**Comment by zghyy** [comment]
I have watched the video you posted on yotube. Policy is used together with Placement Rule and Placement Binding. But I have seen ManagedClusterSet, Placement, PlacementDecision in the [community](https://open-cluster-management.io/concepts/placement/). 

I think these are two different ways of cluster selection and resource distribution. So I just want to know the difference between the two, or the advantages and disadvantages of the two.

These are just my own understanding, if there is any problem, I hope to be corrected

**Comment by mikeshng** [comment]
@zghyy PlacementRule is slowly being deprecated. Placement will be the API going forward. PlacementBinding will stay the same because its a binding for policy to pick which API to use when selecting cluster(s).

It seems like the support for Placement API is now done. https://github.com/open-cluster-management-io/community/issues/63 The instructions on our website has also been updated to reflect this change: https://open-cluster-management.io/getting-started/integration/policy-controllers/#placement-api

@dhaiducek @gparvin can provide more details if needed.

**Comment by zghyy** [comment]
> @zghyy PlacementRule is slowly being deprecated. Placement will be the API going forward. PlacementBinding will stay the same because its a binding for policy to pick which API to use when selecting cluster(s).
> 
> It seems like the support for Placement API is now done. #63 The instructions on our website has also been updated to reflect this change: https://open-cluster-management.io/getting-started/integration/policy-controllers/#placement-api
> 
> @dhaiducek @gparvin can provide more details if needed.

Thank you for your answer, I am already clear about this question.
