### ISSUE TITLE
New repository: multicloud-integrations: First content - Import ManagedClusters into Argo CD

### ISSUE THREAD

**Issue by jnpacker** [open-cluster-management-io/community#92]
I would like to contribute a new kind/controller that references a Placement/PlacementDecision resource to import a ManagedCluster into Argo CD.  

* Placement filters which ManagedClusters to import into an Argo CD.
* The same ManagedCluster name is used.
* The resource kind would be `gitopscluster`
* You can create multiple instances of the resource to target mulitple Argo CD's deployed in the cluster
* This also creates an imported Argo CD cluster that will work with ApplicationSet's and Placement as well as standard Application Deployments
* I was thinking the multicloud-integrations repo. Where other integration's could be added later

**Comment by zychina** [comment]
hello @jnpacker 
  glad to see you again since worked on Bluemix local. For argoCD + OCM, it is great for online application on multiple clusters. 
Two questions:
1. In the solution, there is controller watch placement rule and create ArgoCD cluster and import into ArgoCD namespace. I know ArgoCD working as a "push" mode. For each cluster, there is a cluster secret in ArgoCD namespace for cluster name and kubeconfig. The question is OCM working as a pull mode, how we can get each managed cluster kubeconfig ?
2. If we got kubeconfig someway, then ArgoCD will work on push way, instead of using OCM manifestwork. Right ?

Thank you.

**Comment by zychina** [comment]
3. could you pls show some user experience, what kind of argoCD application/applicationset look like ?  for example, as developer I want to deploy application to two clusters which label with staging.

**Comment by apphe** [comment]
@jnpacker @mikeshng could you please help answer questions above? We can close the issue then. Thanks!

**Comment by mikeshng** [comment]
https://rcarrata.com/openshift/argo-and-acm/

Please see the above blog post about the Argo integration. Thanks.
Since the repo has been created, closing the issue. Please open any further issues or questions in https://github.com/open-cluster-management-io/multicloud-integrations
